# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        args: [ "--config=.configs/commitlint.config.js" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

      - id: no-commit-to-branch
        stages: [ prepare-commit-msg, merge-commit, push ]
        always_run: false

  - repo: https://github.com/mpalmer/action-validator
    rev: v0.5.1
    hooks:
      - id: action-validator
        stages: [ commit-msg ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/pylint/
    rev: v2.14.5
    hooks:
      - id: pylint
        exclude: tests/  # Prevent files in tests/ to be passed in to pylint.

  - repo: local
    hooks:
      - id: check-tox-before-push
        name: check tox before push
        language: script
        entry: .hooks/check-tox.sh
        args: [ "dev" ]
        stages: [ push ]
