- id: run-scripts
  name: Run Scripts
  description: Run your local hook scripts.
  entry: run-scripts
  language: python

- id: document-oriented
  name: document oriented check
  description: If the source file changes, at least one document must be updated.
  entry: document-oriented
  language: python
  always_run: true
  pass_filenames: false
  stages: [ push ]
